//! The serialisable pipeline configuration.
//!
//! The configuration is the stable form of a pipeline: a schema version, an
//! optional seed and an ordered list of stages. It is plain JSON, written by
//! hand or generated by a caller, and it round-trips — what a run reads is what
//! a run writes.
//!
//! ```json
//! {
//!   "version": 1,
//!   "seed": 20260831,
//!   "stages": [
//!     { "transform": "sample", "rate": 0.05 },
//!     { "transform": "fuzz", "distribution": "gaussian", "scale": 0.01, "mode": "relative" },
//!     { "transform": "quantise", "scheme": "bfloat16" }
//!   ]
//! }
//! ```
//!
//! Unknown keys are refused rather than ignored: a misspelt `raet` would
//! otherwise silently sample at a rate nobody asked for.

use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

use super::PipelineError;

/// The schema version of the pipeline configurations this crate reads and
/// writes.
///
/// A configuration carrying any other version is refused rather than read on a
/// guess at where its fields have moved.
pub const PIPELINE_CONFIG_VERSION: u32 = 1;

/// The default target list of a fuzz stage — the same safe default the
/// `--targets` flag carries.
fn default_targets() -> String {
    "inputs".to_string()
}

/// An ordered pipeline of transforms.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PipelineConfig {
    /// The schema version — [`PIPELINE_CONFIG_VERSION`].
    pub version: u32,
    /// The seed every stage seed is derived from; `None` draws one from the
    /// operating system, as the standalone transforms do.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seed: Option<u64>,
    /// The transforms to apply, in the order they are applied.
    pub stages: Vec<PipelineStage>,
}

impl PipelineConfig {
    /// A configuration applying `stages` in order, at the current schema
    /// version and with no seed pinned.
    #[must_use]
    pub const fn new(stages: Vec<PipelineStage>) -> Self {
        Self {
            version: PIPELINE_CONFIG_VERSION,
            seed: None,
            stages,
        }
    }

    /// Pins the seed the run derives every stage seed from.
    #[must_use]
    pub const fn with_seed(mut self, seed: u64) -> Self {
        self.seed = Some(seed);
        self
    }

    /// Reads a configuration from `path`.
    ///
    /// # Errors
    ///
    /// Returns [`PipelineError::Io`] when the file cannot be read,
    /// [`PipelineError::Json`] when it is not a pipeline configuration — an
    /// unknown key included — and whatever [`PipelineConfig::validate`]
    /// rejects it for.
    pub fn load(path: impl AsRef<Path>) -> Result<Self, PipelineError> {
        let path = path.as_ref();
        let bytes = fs::read(path).map_err(|e| PipelineError::io(path, e))?;
        let config: Self =
            serde_json::from_slice(&bytes).map_err(|e| PipelineError::json(path, e))?;
        config.validate()?;
        Ok(config)
    }

    /// Parses a configuration from JSON text.
    ///
    /// # Errors
    ///
    /// Returns [`PipelineError::Json`] when the text is not a pipeline
    /// configuration, and whatever [`PipelineConfig::validate`] rejects it for.
    pub fn from_json(json: &str) -> Result<Self, PipelineError> {
        let config: Self =
            serde_json::from_str(json).map_err(|e| PipelineError::json(Path::new("<json>"), e))?;
        config.validate()?;
        Ok(config)
    }

    /// The configuration as the JSON an operator reads and a run replays.
    ///
    /// # Errors
    ///
    /// Returns [`PipelineError::Json`] when the configuration cannot be
    /// encoded.
    pub fn to_json(&self) -> Result<String, PipelineError> {
        let mut json = serde_json::to_string_pretty(self)
            .map_err(|e| PipelineError::json(Path::new("<json>"), e))?;
        json.push('\n');
        Ok(json)
    }

    /// Checks the configuration before any file is opened.
    ///
    /// # Errors
    ///
    /// Returns [`PipelineError::UnsupportedConfigVersion`] for a schema this
    /// build does not know, [`PipelineError::EmptyPipeline`] when there is
    /// nothing to run, and [`PipelineError::Stage`] for a stage whose
    /// parameters cannot be used.
    pub fn validate(&self) -> Result<(), PipelineError> {
        if self.version != PIPELINE_CONFIG_VERSION {
            return Err(PipelineError::UnsupportedConfigVersion {
                found: self.version,
                expected: PIPELINE_CONFIG_VERSION,
            });
        }
        if self.stages.is_empty() {
            return Err(PipelineError::EmptyPipeline);
        }
        // Planning is the validation: it parses every stage parameter, so an
        // unusable pipeline fails before a corpus file is opened. The seed
        // decides nothing about validity, so any value proves the shape.
        self.plan(0)?;
        Ok(())
    }
}

/// One stage of a pipeline: a transform and the parameters it runs under.
///
/// The wire form names the transform under `transform` and carries its
/// parameters beside it, so a stage reads as the command line it replaces.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "transform", rename_all = "lowercase")]
#[non_exhaustive]
pub enum PipelineStage {
    /// Materialised sampling — keep each record with probability `rate`.
    Sample(SampleStage),
    /// Seeded noise augmentation over the targeted values.
    Fuzz(FuzzStage),
    /// Re-encoding every value under a narrower scheme.
    Quantise(QuantiseStage),
}

impl PipelineStage {
    /// The transform name, as the manifest records it.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            Self::Sample(_) => "sample",
            Self::Fuzz(_) => "fuzz",
            Self::Quantise(_) => "quantise",
        }
    }

    /// The seed this stage pins, when it pins one.
    #[must_use]
    pub const fn seed(&self) -> Option<u64> {
        match self {
            Self::Sample(stage) => stage.seed,
            Self::Fuzz(stage) => stage.seed,
            Self::Quantise(_) => None,
        }
    }
}

/// The parameters of a `sample` stage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SampleStage {
    /// Probability each record is kept, in `(0, 1]`.
    pub rate: f64,
    /// A seed pinned for this stage alone; omitted, it is derived from the
    /// pipeline seed and the stage's position.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seed: Option<u64>,
}

/// The parameters of a `fuzz` stage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FuzzStage {
    /// The noise distribution — `gaussian` or `uniform`.
    pub distribution: String,
    /// The magnitude of the noise; finite and above zero.
    pub scale: f64,
    /// How the noise is applied — `absolute` or `relative`.
    pub mode: String,
    /// Which values are perturbed — `inputs`, `outputs` or `all`.
    #[serde(default = "default_targets")]
    pub targets: String,
    /// Lower bound every perturbed value is held at or above.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clamp_min: Option<f32>,
    /// Upper bound every perturbed value is held at or below.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clamp_max: Option<f32>,
    /// A seed pinned for this stage alone; omitted, it is derived from the
    /// pipeline seed and the stage's position.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seed: Option<u64>,
}

/// The parameters of a `quantise` stage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct QuantiseStage {
    /// The quantisation scheme — currently `bfloat16`.
    pub scheme: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn stages() -> Vec<PipelineStage> {
        vec![
            PipelineStage::Sample(SampleStage {
                rate: 0.05,
                seed: None,
            }),
            PipelineStage::Quantise(QuantiseStage {
                scheme: "bfloat16".to_string(),
            }),
        ]
    }

    #[test]
    fn names_every_stage_after_its_transform() {
        assert_eq!(
            stages().iter().map(PipelineStage::name).collect::<Vec<_>>(),
            vec!["sample", "quantise"]
        );
    }

    #[test]
    fn round_trips_through_json_keeping_the_stage_order() {
        let config = PipelineConfig::new(stages()).with_seed(7);

        let json = config.to_json().expect("encode");
        let parsed = PipelineConfig::from_json(&json).expect("decode");

        assert_eq!(parsed, config);
        assert_eq!(parsed.stages[0].name(), "sample");
        assert_eq!(parsed.stages[1].name(), "quantise");
    }

    #[test]
    fn leaves_an_unpinned_seed_out_of_the_serialised_form() {
        let json = PipelineConfig::new(stages()).to_json().expect("encode");

        assert!(!json.contains("seed"), "{json}");
    }

    #[test]
    fn defaults_the_fuzz_targets_to_the_safe_one() {
        let config = PipelineConfig::from_json(
            r#"{"version":1,"stages":[{"transform":"fuzz","distribution":"uniform","scale":0.5,"mode":"absolute"}]}"#,
        )
        .expect("decode");

        let PipelineStage::Fuzz(stage) = &config.stages[0] else {
            panic!("a fuzz stage");
        };
        assert_eq!(stage.targets, "inputs");
    }

    #[test]
    fn refuses_a_misspelt_stage_key_rather_than_ignoring_it() {
        let error = PipelineConfig::from_json(
            r#"{"version":1,"stages":[{"transform":"sample","raet":0.5}]}"#,
        )
        .expect_err("a misspelt key is refused");

        assert!(matches!(error, PipelineError::Json { .. }), "{error:?}");
    }

    #[test]
    fn refuses_an_unknown_transform() {
        let error =
            PipelineConfig::from_json(r#"{"version":1,"stages":[{"transform":"shuffle"}]}"#)
                .expect_err("shuffle is not a transform this build offers");

        assert!(matches!(error, PipelineError::Json { .. }), "{error:?}");
    }

    #[test]
    fn reports_the_seed_a_stage_pins() {
        let pinned = PipelineStage::Fuzz(FuzzStage {
            distribution: "uniform".to_string(),
            scale: 0.5,
            mode: "absolute".to_string(),
            targets: default_targets(),
            clamp_min: None,
            clamp_max: None,
            seed: Some(3),
        });

        assert_eq!(pinned.seed(), Some(3));
        assert_eq!(stages()[1].seed(), None, "quantise takes no seed");
    }
}
